steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'ubuntu'
  args: ['pwd']
- name: 'ubuntu'
  args: ['ls']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gsutil cp -r dist/* gs://pwbuilds-artifacts']
