steps:i
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'ubuntu'
  args: ['bash', './workspace/node_modules/gulp/bin/gulp.js build']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gsutil cp -r dist/* gs://pwbuilds-artifacts']
